context:
  version: "1.1.4"

package:
  name: xauth
  version: ${{ version }}

source:
  url: https://www.x.org/pub/individual/app/xauth-${{ version }}.tar.xz
  sha256: e9318141464ad7b4dc0f8564a580f0d20f977c85a388cc40d5a766206151c690

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - xorg-kbproto
    - xorg-libx11
    - xorg-libxmu
    - xorg-libxext
    - xorg-libxmu
    - xorg-xextproto
    - xorg-xproto
    - if: linux
      then:
        - libxcb
        - xorg-libxdmcp

tests:
  - script:
      - xauth -h 2>&1 | grep -q "usage: "xauth \\[-options ...\\] \\[command arg ...\\]\""

about:
  license: MIT
  license_file: COPYING
  summary: X.Org authorization settings program
  homepage: https://xorg.freedesktop.org/

extra:
  recipe-maintainers:
    - danielnachun
